mysql:
  master:
    user: 'root'
    password: 'root'
    host: 'localhost'
    dbname: 'silexrest'
  slaves:
    0:
      user: 'root'
      password: 'root'
      host: 'localhost'
      dbname: 'silexrest'

base.url: ''